extension: "nudge"
userid: 123
appId: 1234
userpersona: "observability"
serviceNames:
  dynatrace:
    persona: 'observability'
    commands:
      - commandName: "Top 5 responses by application"
        queryString: "builtin:service.response.client:splitBy('dt.entity.service'):max:limit(5):fold(max):names"
        dimensionName: "dt.entity.service"
      - commandName: "Top 3 CPU usage by application"
        queryString: "builtin:service.response.client:splitBy('dt.entity.service'):max:limit(3):fold(max):names"
        dimensionName: "serviceName"
  blazemeter:  
    persona: 'performance'
    requestInput:
      - workspaceId
      - projectId
apiEndpoints:
  dynatrace: "https://dev.nudgegenai.mlc.cld1np.thehartford.com/dynatrace"
  blazemeter: "https://dev.nudgegenai.mlc.cld1np.thehartford.com/blazemeter"
