extension: "nudge"
userid: 123
serviceNames:
  dynatrace:
    commands:
      - commandName: "Top 5 responses by application"
        queryString: "builtin:service.response.client:splitBy('dt.entity.service'):max:limit(5):fold(max):names"
      - commandName: "Top 3 CPU usage by application"
        queryString: "builtin:service.response.client:splitBy('dt.entity.service'):max:limit(3):fold(max):names"
  blazemeter:
    requestInput:
      - workspacId
      - projectId
apiEndpoints:
  dynatrace: "https://dev.nudgegenai.mlc.cld1np.thehartford.com/dynatrace"
  blazemeter: "https://dev.nudgegenai.mlc.cld1np.thehartford.com/blazemeter"
